function createHotelView(hotelInformation){var cardColumnDiv=document.createElement('div');cardColumnDiv.classList.add('col','s6','m3','l4');var cardDiv=document.createElement('div');cardDiv.classList.add('card','small');var imageDiv=document.createElement('div');imageDiv.classList.add('image');var image=document.createElement('img');image.classList.add('circle','responsive-img','hotel-image');image.setAttribute('src',hotelInformation.hotelInfo.hotelImageUrl);image.setAttribute('alt',hotelInformation.hotelInfo.hotelName);var imageTitleDiv=document.createElement('div');imageTitleDiv.classList.add('card-content','hotel-title');var hotelName=document.createElement('h6');var hotelNameUrl=document.createElement('a');hotelNameUrl.innerHTML=hotelInformation.hotelInfo.hotelName;hotelNameUrl.href=decodeURIComponent(hotelInformation.hotelUrls.hotelInfositeUrl);hotelName.appendChild(hotelNameUrl);hotelName.classList.add('hotel-name');var hotelDestination=document.createElement('p');hotelDestination.innerHTML=hotelInformation.hotelInfo.hotelStreetAddress
+','+hotelInformation.hotelInfo.hotelLongDestination;hotelDestination.innerHTML+='<br/>';hotelDestination.innerHTML+=hotelInformation.destination.longName+' - '
+hotelInformation.destination.regionID;imageTitleDiv.appendChild(hotelName);imageTitleDiv.appendChild(hotelDestination);var hotelInfoDiv=document.createElement('div');hotelInfoDiv.classList.add('hotel-info');var ratingDiv=document.createElement('div');ratingDiv.classList.add('rating');var ratingValue=document.createElement('p');ratingValue.innerHTML=hotelInformation.hotelInfo.hotelGuestReviewRating
+'/5';ratingValue.innerHTML+='<br/>';ratingValue.innerHTML+=hotelInformation.hotelInfo.hotelReviewTotal
+' reviews';var starRatingParent=document.createElement('div');starRatingParent.classList.add('star-rating-parent');var greyStarDiv=document.createElement('div');greyStarDiv.classList.add('grey-star');var greyStarImg=document.createElement('img');greyStarImg.setAttribute('src','images/rating.png');greyStarImg.setAttribute('alt',hotelInformation.hotelInfo.hotelStarRating);var yellowStarDiv=document.createElement('div');yellowStarDiv.style.width=(13.8*hotelInformation.hotelInfo.hotelStarRating)
+'px';yellowStarDiv.style.overflow='hidden';var yellowStarImg=document.createElement('img');yellowStarImg.setAttribute('src','images/rating-filled.png');greyStarDiv.appendChild(greyStarImg);yellowStarDiv.appendChild(yellowStarImg);starRatingParent.appendChild(greyStarDiv);starRatingParent.appendChild(yellowStarDiv);ratingDiv.appendChild(starRatingParent);yellowStarDiv.classList.add('yellow-star');ratingDiv.appendChild(ratingValue);var pricingDiv=document.createElement('div');pricingDiv.classList.add('pricing');var totalPrice=document.createElement('span');totalPrice.style.color='green';totalPrice.innerHTML=hotelInformation.hotelPricingInfo.totalPriceValue
+' '+hotelInformation.hotelPricingInfo.currency;var oldPrice=document.createElement('strike');oldPrice.innerHTML=hotelInformation.hotelPricingInfo.crossOutPriceValue;pricingDiv.appendChild(oldPrice);pricingDiv.appendChild(totalPrice);hotelInfoDiv.appendChild(pricingDiv);var cardActionDiv=document.createElement('div');cardActionDiv.classList.add('card-action');var startDateObject=hotelInformation.offerDateRange.travelStartDate;var startDate=startDateObject[2]+'/'+startDateObject[1]+'/'
+startDateObject[0];var endDateObject=hotelInformation.offerDateRange.travelEndDate;var endDate=endDateObject[2]+'/'+endDateObject[1]+'/'
+endDateObject[0];var dateDiv=document.createElement('div');dateDiv.innerHTML=startDate+' - '+endDate;dateDiv.style.textAlign='center';cardActionDiv.appendChild(dateDiv);hotelInfoDiv.appendChild(ratingDiv);imageDiv.appendChild(image);imageDiv.appendChild(imageTitleDiv);cardColumnDiv.appendChild(cardDiv);cardDiv.appendChild(imageDiv);cardDiv.appendChild(hotelInfoDiv);cardDiv.appendChild(cardActionDiv);document.getElementById('hotels').appendChild(cardColumnDiv);}
function generateSearchQuery(){var searchQuery='destination='
+document.getElementById("destination").value;searchQuery+='&tripDate='+document.getElementById("tripDate").value;searchQuery+=':'
+$("#"+"start-date-order"+" option:selected").text();searchQuery+='&stay='+document.getElementById("stay").value;searchQuery+='&guestRating='
+document.getElementById("guestRating").value;searchQuery+=':'
+$("#"+"guest-rating-order"+" option:selected").text();searchQuery+='&totalRating='
+document.getElementById("totalRating").value;searchQuery+=':'
+$("#"+"total-rating-order"+" option:selected").text();searchQuery+='&starRating='+document.getElementById("starRating").value;searchQuery+=':'
+$("#"+"star-rating-order"+" option:selected").text();searchQuery+='&price='+document.getElementById("price").value;searchQuery+=':'+$("#"+"price-order"+" option:selected").text()
+'&';document.getElementById("hotels").innerHTML="";return searchQuery;}
function fetchHotelInfo(searchQuery){var queryString;if(typeof searchQuery==='undefined'){queryString='';}else{queryString='?'+searchQuery;};var url=window.location+'services/getHotels'+queryString;$.getJSON(url,function(data){var hotelInformation=data.offers.Hotel;hotelInformation.forEach(function(element){createHotelView(element);});});}
function search(){fetchHotelInfo(generateSearchQuery());}