function createHotelView(hotelInformation){var startDateObject=hotelInformation.offerDateRange.travelStartDate;var endDateObject=hotelInformation.offerDateRange.travelEndDate;var hotelCard='<div class="col s6 m3 l4"> <div class="card small"> <div class="image"> <img class="circle responsive-img hotel-image"  src="'
+hotelInformation.hotelInfo.hotelImageUrl+'" alt="'+hotelInformation.hotelInfo.hotelName+'"/> <div class="card-content hotel-title"> <h6 class="hotel-name"> <a href="'+
decodeURIComponent(hotelInformation.hotelUrls.hotelInfositeUrl)+'">'+hotelInformation.hotelInfo.hotelName+'</a> </h6> <p>'+
hotelInformation.hotelInfo.hotelStreetAddress+','+hotelInformation.hotelInfo.hotelLongDestination+'<br />'+hotelInformation.destination.longName+' - '+hotelInformation.destination.regionID+'</p> </div> </div> <div class="hotel-info"> <div class="pricing"> <strike>'+hotelInformation.hotelPricingInfo.crossOutPriceValue+'</strike> <span style="color:green;">'+hotelInformation.hotelPricingInfo.totalPriceValue+' '+
hotelInformation.hotelPricingInfo.currency+'</span> </div> <div class="rating"> <div class="star-rating-parent">  <div class="grey-star">  <img src="images/rating.png" alt="'+
hotelInformation.hotelInfo.hotelStarRating+'" /> </div> <div style="width:'+13.8*hotelInformation.hotelInfo.hotelStarRating+'px;'+' overflow:hidden;" class="yellow-star"> <img src="images/rating-filled.png" /> </div> </div> <p>'+
hotelInformation.hotelInfo.hotelGuestReviewRating+'/5 <br />'+hotelInformation.hotelInfo.hotelReviewTotal+' reviews'+'</p> </div> </div> <div class="card-action"> <div style="text-align:center;">'+startDateObject[2]+'/'+startDateObject[1]+'/'+startDateObject[0]+' - '+endDateObject[2]+'/'+endDateObject[1]+'/'+endDateObject[0]+'</div> </div> </div> </div>';document.getElementById('hotels').insertAdjacentHTML('beforeend',hotelCard);}
function generateSearchQuery(){var searchQuery=' destination='+document.getElementById("destination").value;searchQuery+='&tripDate='+document.getElementById("tripDate").value;searchQuery+=':'+$("#"+"start-date-order"+" option:selected").text();searchQuery+='&stay='+document.getElementById("stay").value;searchQuery+='&guestRating='+document.getElementById("guestRating").value;searchQuery+=':'+$("#"+"guest-rating-order"+" option:selected").text();searchQuery+='&totalRating='+document.getElementById("totalRating").value;searchQuery+=':'+$("#"+"total-rating-order"+" option:selected").text();searchQuery+='&starRating='+document.getElementById("starRating").value;searchQuery+=':'+$("#"+"star-rating-order"+" option:selected").text();searchQuery+='&price='+document.getElementById("price").value;searchQuery+=':'+$("#"+"price-order"+" option:selected").text()+'&';document.getElementById("hotels").innerHTML="";return searchQuery;}
function fetchHotelInfo(searchQuery){var queryString;if(typeof searchQuery==='undefined'){queryString='';}else{queryString='?'+searchQuery;};var url=window.location+'services/getHotels'+queryString;$.getJSON(url,function(data){var hotelInformation=data.offers.Hotel;hotelInformation.forEach(function(element){createHotelView(element);});});}
function search(){fetchHotelInfo(generateSearchQuery());}